### ISSUE TITLE
Design: Determine how to manage component lifecycle

### ISSUE THREAD

**Issue by pdf** [gopherjs/vecty#115]
In the course of #114, issues with current methods for instantiating child components were identified that will result in hard to reason about behaviour for users.

This issue is to track design discussions on methods to alleviate these issues.

My preference is to remove the need for the `Restorer` interface entirely by somehow retaining a reference to a child component between parent renders, though I'm not sure exactly what this looks like at this stage.

**Comment by slimsag** [comment]
I still need to look into this, I haven't had a chance yet. I am very keen to try and removing the `Restorer` interface, but I'm not sure how it would look or work exactly. I'm very open to anyone proposing ideas here.

**Comment by pdf** [comment]
I've been thinking about this a little, and I think I can see a way for us to maintain the same children across renders, but even if we do this, I'm not sure how to determine which values to apply from the new component instance, due to Go's zero values.

If we just assume for now that components are transparently persisted across renders, consider:

```go
type InnerComponent struct {
    Boolean bool
    String string
    privateState string
}

func (c *MyComponent) Render() *vecty.HTML {
    c.boolean = !c.boolean
    
    return elem.Div(
        &InnerComponent{Boolean: c.boolean},
    )
}
```

I can't see how you would determine which fields need to be modified on the stored `InnerComponent` pointer each render.  There are some ways we can handle this part of the problem, but I'm not sure I'm overly happy with any of them:

1. Establish a convention that all public fields are always overwritten during render, and that internal state must use private fields.
2. Require components to be rendered via a function wrapper with a properties `map[string]interface{}` as an argument that is used to set field values via reflection.
3. Require internal state to be managed via manipulation of a structure that's stored on the `vecty.Core`, using a method similar to `setState` from React, and have this structure be the only data that is persisted between renders.

**Comment by slimsag** [comment]
Thanks for the writeup @pdf -- I appreciate you spending the time to look into this and present possible options. I agree with what you wrote here. My thoughts on these three options:

1. Sounds like it would be confusing, since public and private fields already have an important semantic (and describing it to newcomers is non-obvious / difficult). IIRC we also currently copy the fields using reflection, meaning those fields would have to be public (or users MUST implement Copy)?
2. Sounds like it would work, but sounds somewhat ugly.
3. By far sounds like the best option of these three to me. Of course, it would most likely have to be an untyped structure (`interface{}`) which would be unfortunate.

I have another idea: struct field tags? i.e.

```Go
type InnerComponent struct {
    Boolean bool
    String string // TODO: Is it state or a property?
    privateState string `vecty:"state"`
}
```

Then exported/unexported status does not matter, and only fields tagged as `state` are carried over. For simplicity, users could declare `type InnerComponentState struct` and embed it:

```Go
type InnerComponent struct {
    Boolean bool
    String string // TODO: Is it state or a property?
    InnerComponentState `vecty:"state"`
}
```

So that they only have to write the tag once.

What do you think of this idea in comparison to your third idea?

**Comment by pdf** [comment]
Your appraisals of the options I presented are pretty much identical to my own, which is why I didn't like them much.

Though I don't expect we will implement option __1__, explanation for clarity:

> IIRC we also currently copy the fields using reflection, meaning those fields would have to be public (or users MUST implement Copy)?

My concept for implementing the base for this feature would store a pointer from the previous render, so unexported fields would persist, and we would be able to set the exported fields.  For the current internal implementation of `Copier`, we copy the struct value rather than individual fields, so we get all the memory.

---

Struct tags are a rather good option, with the caveat that unexported fields can't be written via `reflect` without `unsafe`, so the first example doesn't work and state fields must be exported.

Using struct tags does still mean some less than obvious interactions similar to those discussed in https://github.com/gopherjs/vecty/pull/114#issuecomment-302859808, though this might be acceptable with documentation, and it does improve visibility and obviousness of the side-effect, since the documentation for the tag should detail the interaction, and the distraction of `Restorer` boilerplate is removed.

**Comment by slimsag** [comment]
> Struct tags are a rather good option, with the caveat that unexported fields can't be written via reflect without unsafe, so the first example doesn't work and state fields must be exported.

Good point; I think that is acceptable (that we require users to export them). Let's call this "common mistake 1".

> Using struct tags does still mean some less than obvious interactions similar to those discussed in #114 (comment), though this might be acceptable with documentation, and it does improve visibility and obviousness of the side-effect, since the documentation for the tag should detail the interaction, and the distraction of Restorer boilerplate is removed.

I assume you are speaking specifically about "what if a user instantiates a component and specifies a struct field -- even though it has `vecty:"state"` set on it?" (if you're referencing other 'less than obvious interactions', they aren't obvious to me here 😜). Let's call this "common mistake 2".

I think relying on documentation for both of these mistakes will generally be good enough. After all, in both cases the user will have gone through this thought process:

1. "Why are my struct fields not carried across renders?" -> "Oh, because I'm instantiating the component again. Ok, the docs say struct field tags fix this. Cool."
2. "Why aren't the values carried over still, even though they have the tag?" -> "Oh, because they're not exported. OK."
3. "Why are my values overwritten?" -> "Oh, because I manually specified them at instantiation time."

To make things a bit more obvious, I think that I can (and most likely will) end up writing something akin to `vecty vet` that makes such issues obvious (both of these common user mistakes should be easy to detect, because of the presence of a struct field).

I'm sure there are things I'm not thinking of with this approach: e.x. do people implementing `Copier` need to copy state fields, or not? But at this point they will probably only crop up through writing an actual implementation. I think this path (struct fields) is the way to go.

**Comment by pdf** [comment]
> 3. "Why are my values overwritten?" -> "Oh, because I manually specified them at instantiation time."

The surprising behaviour here is actually the opposite - the manually specified values at the instantiation site are overwritten by the previous render values for `state` fields.  It would probably be _less_ surprising if it was the other way around.

> I'm sure there are things I'm not thinking of with this approach: e.x. do people implementing Copier need to copy state fields, or not?

I don't think this feature will intersect with `Copier` at all, my concerns are still around usability but I can take a pass at this approach.

---

There is one final alternative that I think we should strongly consider though - require users to maintain their own component references if they want their components to be stateful.

To illustrate what I'm talking about:

```go
type InnerComponent struct {
        vecty.Core
        inc int
}

func (c *InnerComponent) Render() *vecty.HTML {
        c.inc++

        return elem.Span(
                vecty.Text(strconv.Itoa(c.inc)),
        )
}

type MyComponent struct {
        vecty.Core
        statefulComponent *InnerComponent
}

func (c *MyComponent) Render() *vecty.HTML {
        if c.statefulComponent == nil {
                c.statefulComponent = &InnerComponent{}
        }

        return elem.Div(
                &InnerComponent{},   // This component instance will lose internal state between renders, and always render 0
                c.statefulComponent, // This component instance will maintain internal state between renders, and increment the counter
        )
}
```

We simply make it clear that if users want statefulness, they need to maintain a reference across renders.  This removes `Restorer`, and is all regular Go that users should be able to grok, without additional surprises.

**Comment by slimsag** [comment]
> The surprising behaviour here is actually the opposite - the manually specified values at the instantiation site are overwritten by the previous render values for state fields. It would probably be less surprising if it was the other way around.

Fair enough.

> There is one final alternative that I think we should strongly consider though ...

That's a _very_ compelling idea. Thank you for sharing! I've had to think about this from a couple of angles:

1. I thought that initialization of a list of items might be more complex looking with this solution, but it turned out not to be when I wrote it down in code.
2. I think that this approach _may_ be worse, because it makes it easy for newcomers to accidently introduce statefulness in their components (simply _because_ they are not constantly being instantiated).
3. Perhaps the biggest problem, addition of state after the fact (more on this below).

Take for example this component:

```Go
type MyComponent struct {
	vecty.Core
}

func (c *MyComponent) Render() *vecty.HTML {
	return elem.Div(
		vecty.Text("Hello World"),
	)
}
```

As is, this component could be easily used by someone else if it was e.g. put into a Go package named `bootstrap`:

```Go
type PageComponent struct {}

func (p *PageComponent) Render() *vecty.HTML {
	return elem.Body(
		&bootstrap.MyComponent{},
	)
}
```

The problem comes when `bootstrap.MyComponent` is modified to be stateful:

```Go
type MyComponent struct {
	vecty.Core
	statefulComponent *InnerComponent
}

func (c *MyComponent) Render() *vecty.HTML {
	if c.statefulComponent == nil {
		c.statefulComponent = &InnerComponent{}
	}
	return elem.Div(
		vecty.Text("Hello World"),
		c.statefulComponent,
	)
}
```

Now the caller must also use this as a stateful component:

```Go
type PageComponent struct {
	statefulMyComponent *bootstrap.MyComponent
}

func (p *PageComponent) Render() *vecty.HTML {
	if p.statefulMyComponent == nil {
		p.statefulMyComponent = &bootstrap.MyComponent{}
	}
	return elem.Body(
		p.statefulMyComponent,
	)
}
```

Now, maybe we say that the above is expected / not that bad. But what is worse is that any user of `PageComponent` (if it was not returning a body element) would also need to utilize that component as stateful in just the same way. If `MyComponent` is, say, 7 components deep this becomes quite a difficult change to make. In a real codebase I imagine it would be much worse / more deep than 7 components.

I might be missing something obvious where this problem could be avoided, but at current I see no way around this problem with this approach. In contrast with the struct field tags, Vecty itself is doing the field copying and could transparently handle this behind the scenes (that is, the copy is done by Vecty and thus all the parent components don't need to be modified).

It's late here and I'm quite tired, so if I've missed the ball on anything here let me know! I'd be very glad to be proven wrong about this! 😄

**Comment by pdf** [comment]
> 2. I think that this approach may be worse, because it makes it easy for newcomers to accidently introduce statefulness in their components (simply because they are not constantly being instantiated).

Is this necessarily a bad thing?

> 3. Perhaps the biggest problem, addition of state after the fact

You are correct - I should have mentioned this limitation, as I was aware of it.

I will say that I have been using this pattern (as I wasn't aware of the intended function of `Restorer`), and haven't found it too onerous.  However this may be due to a combination of factors in my application:

- using my router experiment, which results in components at each level of route nesting being persistent by default, which in turn limits explicit child depth for any individual component a lot
- having more reliable lifecycle (mount/unmount) events
- most rerenders being triggered by either the router, or via a redux-style dispatcher, so that rerenders are generally highly targeted, rather than hitting the full tree
- writing all components locally

Obviously these factors will not apply to all users though.

If we do end up going with the tag implementation, do you think there's merit in reversing the tag notation, so that we instead denote fields that should be set from the parent context (`props` in React parlance), rather than fields that are persisted (`state`)?  This would enable persistence by default, and allow persistence for unexported fields.  Does this feel too much like magic?

With either tag direction, the tag pattern still feels somewhat clumsy to me, due to the interaction with fields set from the parent, because you often want to propagate props from parent to child (and it's not clear to me how users should synchronize props->state between renders), and because of the loss of private state between renders.

I guess users always have the option of implementing the explicit reference pattern above if they want fully persistent components and the ability to modify state fields directly from the parent between renders, but if feels bad to have multiple patterns for this. :confused:

**Comment by slimsag** [comment]
> Is this necessarily a bad thing?

I just stated it as a downside. I certainly don't think it's a _good_ thing, but I also don't think it would block this approach.

> I will say that I have been using this pattern (as I wasn't aware of the intended function of Restorer), and haven't found it too onerous.

Thanks for the summary of why you haven't found this approach too bad. I still currently fear that going with this approach would make writing reusable component libraries, that are shared more broadly with the community, quite hard. That's not to say that I am throwing out the idea, just that I need more convincing before choosing it.

> I guess users always have the option of implementing the explicit reference pattern above if they want fully persistent components and the ability to modify state fields directly from the parent between renders, but it feels bad to have multiple patterns for this. 😕

I really dislike suggesting that there can be two different patterns. If anything, we might outright try to prevent using multiple patterns. Or at the least, say that it's kind of like semicolons in Go (you can, but... you really shouldn't).

I agree that the tag approach still feels a bit clumsy / strange... especially now that I am coming back to this a few days later. I think we should think about this a bit more.

Another option that might be better that popped into my mind just now was that we might have a _single_ tag accepted in a struct. For example, only the first `vecty:"state"` tag is recognized and only that field is copied over. This would look like:

```Go
type myComponentState struct {
	a string
	b string
}

type MyComponent struct {
	PropA, propB string
	State myComponentState `vecty:"state"`
}
```

Or more concisely:

```Go
type MyComponent struct {
	PropA, propB string
	State struct {
		a string
		b string
	} `vecty:"state"`
}
```

The reason this might be useful is because it removes a lot of ambiguity around which things are properties or state, and how exactly the two interact. This option is kind of like the earlier option 3 you proposed:

> Require internal state to be managed via manipulation of a structure that's stored on the vecty.Core, using a method similar to setState from React, and have this structure be the only data that is persisted between renders.

With the exception that it is strongly typed and clearly a part of your component struct.

**Comment by pdf** [comment]
> I really dislike suggesting that there can be two different patterns.

In a way, this is nearly unavoidable, since components behave differently depending on how they're instantiated.  Users will want to pass component references around (#78 and similar use-cases<sup>[1](#ft1)</sup>), and references that persist across renders will behave differently to those that are instantiated each pass  (unless vecty implements magic to contravene this for the latter case).

> Another option that might be better that popped into my mind just now was that we might have a single tag accepted in a struct.

I'm not sure this really needs to be explicit - if the documentation only provides examples similar to the last one you posted, most users will just implement it that way, and those that don't may have reasons we haven't thought of.

---

<sup id="ft1">1</sup> A simple use-case that comes to mind is wanting a button in one component to trigger an action on a nested component, without using a dispatcher.

**Comment by slimsag** [comment]
> In a way, this is nearly unavoidable, since components behave differently depending on how they're instantiated. Users will want to pass component references around (#78 and similar use-cases1), and references that persist across renders will behave differently to those that are instantiated each pass (unless vecty implements magic to contravene this for the latter case).

Interesting point, I hadn't considered how component references play into this. If I understand it correctly, the only difference is that a referenced component can store state without a `vecty:"state"` tag and the parent is responsible for propagating it. If I'm correct about this, I could still catch it with a linter by checking whether or not a component mutates struct fields without a `vecty:"state"` tag (ofc. there may be edge cases / false positives here).

Overall I'm not too worried about that, then. We can just clearly document that component state should only be modified if the field has `vecty:"state"` on it.

> I'm not sure this really needs to be explicit - if the documentation only provides examples similar to the last one you posted, most users will just implement it that way, and those that don't may have reasons we haven't thought of.

That's a good point, I'm fine with taking that approach.

I think using this struct field tag pattern is enough to combat the problems you described earlier though (reversing the tag notation, lack of clarity about how to synchronize props->state between renders). Would you agree or disagree with that?

> As it seems like this issue may take some time to work out, I think I'd like to try and get the remainder of the testing sorted out, so that we can finish integrating some other improvements to rendering that I have in my pipeline?

At this point I'd be glad to go with the struct field tag approach, but of course implementing this may still be non-trivial (and maybe you have other concerns about this approach). I'm glad to go with the remainder of testing first, or maybe even in parallel to this issue (totally up to you). I still haven't had a chance to look into the testing situation yet, though. I apologize for this. I might have time this weekend.

**Comment by pdf** [comment]
> Interesting point, I hadn't considered how component references play into this. If I understand it correctly, the only difference is that a referenced component can store state without a vecty:"state" tag and the parent is responsible for propagating it.

> I think using this struct field tag pattern is enough to combat the problems you described earlier though (reversing the tag notation, lack of clarity about how to synchronize props->state between renders). Would you agree or disagree with that?

There's a bit to unpack here, I think the best way to illustrate is to write a set of examples demonstrating all of the interactions.  I'll try and find some time in the next day or so.

**Comment by pdf** [comment]
Sorry for the extreme delay @slimsag - I'm rather short of spare time recently.  I'll just start posting one comment per issue/quirk/pattern, as I'm not sure I have enough time to work through all of them right now.  That way we can at least keep the conversation moving.

1. Problems with props->state synchronization.  Thinking about this a little, there is a way to do sync, but it's non-obvious.

Naive implementation:
```go
type StatefulComponent struct {
        vecty.Core
        InitialToggle bool
        State         struct {
                Toggle bool
        } `vecty:"state"`
}

func (c *StatefulComponent) Render() *vecty.HTML {
        if c.State.Toggle != c.InitialToggle {
                c.State.Toggle = c.InitialToggle // This is wrong - State.Toggle may have changed between renders, and should not be clobbered.
        }

        return elem.Button(
                vecty.If(!c.State.Toggle, vecty.Text("Inactive")),
                vecty.If(c.State.Toggle, vecty.Text("Active")),
                event.Click(c.toggle),
        )
}

func (c *StatefulComponent) toggle(e *vecty.Event) {
        c.State.Toggle = !c.State.Toggle
        vecty.Rerender(c)
}

type MyComponent struct {
        vecty.Core
}

func (c *MyComponent) Render() *vecty.HTML {
        return elem.Div(
                &StatefulComponent{InitialToggle: true},
        )
}
```

Since the previous value for InitialToggle is lost between renders with this style of instantiation, users actually need to track both fields inside state to support correct propagation of fields from parent to child:
```go
type StatefulComponent struct {
        vecty.Core
        InitialToggle bool
        State         struct {
                Toggle bool
                InitialToggle bool
        } `vecty:"state"`
}

func (c *StatefulComponent) Render() *vecty.HTML {
        if c.State.InitialToggle != c.InitialToggle {
                c.State.Toggle = c.InitialToggle
        }

        return elem.Button(
                vecty.If(!c.State.Toggle, vecty.Text("Inactive")),
                vecty.If(c.State.Toggle, vecty.Text("Active")),
                event.Click(c.toggle),
        )
}
```

One option to avoid users doing this manually might be to expose a method to access the previous component copy, but that doesn't seem very clean either (return value would always need type assertion).

Other comments to follow.

**Comment by pdf** [comment]
2. Differences in behaviour between persistent component references and instantiating each render pass.

Below is an example of a scenario where a user may decide that they want a persistent component reference to share between multiple children (so that `StatefulComponent` may be rendered inside `ToggleContainer`, but triggered from `ToggleActor`):
```go
type Toggler interface {
        vecty.Component
        Toggle()
}

type StatefulComponent struct {
        vecty.Core
        ParentToggle bool
        State        struct {
                toggle       bool
                parentToggle bool
        } `vecty:"state"`
}

func (c *StatefulComponent) Toggle() {
        c.State.toggle = !c.State.toggle
        vecty.Rerender(c)
}

func (c *StatefulComponent) Render() *vecty.HTML {
        if c.State.parentToggle != c.ParentToggle {
                c.State.toggle = c.ParentToggle
                c.State.parentToggle = c.ParentToggle
        }

        return elem.Span(
                vecty.If(!c.State.toggle, vecty.Text("Inactive")),
                vecty.If(c.State.toggle, vecty.Text("Active")),
        )
}

type ToggleContainer struct {
        vecty.Core
        ToggleComponent Toggler
}

func (c *ToggleContainer) Render() *vecty.HTML {
        return elem.Div(
                elem.Span(vecty.Text(`Current status: `)),
                c.ToggleComponent,
        )
}

type ToggleActor struct {
        vecty.Core
        ToggleComponent Toggler
}

func (c *ToggleActor) onClick(e *vecty.Event) {
        c.ToggleComponent.Toggle()
}

func (c *ToggleActor) Render() *vecty.HTML {
        return elem.Button(
                vecty.Text(`Toggle`),
                event.Click(c.onClick),
        )
}

type MyComponent struct {
        vecty.Core
        ParentProp      bool
        ToggleComponent *StatefulComponent
}

func (c *MyComponent) Render() *vecty.HTML {
        if c.ToggleComponent == nil {
                c.ToggleComponent = &StatefulComponent{ParentToggle: c.ParentProp}
        } else if c.ToggleComponent.ParentToggle != c.ParentProp {
                c.ToggleComponent.ParentToggle = c.ParentProp
        }

        return elem.Div(
                &ToggleContainer{ToggleComponent: c.ToggleComponent},
                &ToggleActor{ToggleComponent: c.ToggleComponent},
        )
}
```

The `StatefulComponent` should still work using similar logic to `1` above, however it doesn't _require_ explicit state to function:
```go
type StatefulComponent struct {
        vecty.Core
        ParentToggle     bool
        prevParentToggle bool
        toggle           bool
}

func (c *StatefulComponent) Toggle() {
        c.toggle = !c.toggle
        vecty.Rerender(c)
}

func (c *StatefulComponent) Render() *vecty.HTML {
        if c.prevParentToggle != c.ParentToggle {
                c.toggle = c.ParentToggle
                c.prevParentToggle = c.ParentToggle
        }

        return elem.Span(
                vecty.If(!c.toggle, vecty.Text("Inactive")),
                vecty.If(c.toggle, vecty.Text("Active")),
        )
}
```

I'm a little concerned that this difference in behaviour may be difficult to explain, and may be a source of confusion.

---

I'll need to have a think on whether there are other quirks.

**Comment by pdf** [comment]
@slimsag any thoughts?

**Comment by slimsag** [comment]
Sorry for the delays here @pdf -- and thanks for the ping!

First, I _really_ appreciate you writing these up. One thing that is now clear to me is that, at the very least, I have not given this issue the time it deserves and my assumption about the struct tag approach working fine for most cases was wrong.

I'll respond to these two individually:

---

> 1. Problems with props->state synchronization. Thinking about this a little, there is a way to do sync, but it's non-obvious.

If I understand your first example correctly (I fear I really do not), the general problem statement would be like:

> A parent component want's to specify the default toggle state for a toggle button component, which then of course changes it's own toggle state based on the user clicking the button.

My gut tells me you must be demonstrating something else here / that I do not understand the problem you're showing off in this code. In your first 'naive implementation', `StatefulComponent` isn't actually stateful, as you already showed with your comment:

```
        if c.State.toggle != c.ParentToggle {
                c.State.toggle = c.ParentToggle // This is wrong - State.Toggle may have changed between renders, and should not be clobbered.
        }
```

If I assume that the problem statement I wrote above is correct, then I would assume the naive _and_ correct implementation to look like:

```diff
type StatefulComponent struct {
        vecty.Core
        ParentToggle bool
        State         struct {
                toggle bool
        } `vecty:"state"`
}

func (c *StatefulComponent) Render() *vecty.HTML {
-        if c.State.toggle != c.ParentToggle {
-                c.State.toggle = c.ParentToggle // This is wrong - State.Toggle may have changed between renders, and should not be clobbered.
-        }

        return elem.Button(
                vecty.If(!c.State.toggle, vecty.Text("Inactive")),
                vecty.If(c.State.toggle, vecty.Text("Active")),
                event.Click(c.toggle),
        )
}

func (c *StatefulComponent) toggle(e *vecty.Event) {
        c.State.toggle = !c.State.toggle
        vecty.Rerender(c)
}

+func NewStatefulComponent(parentToggle bool) *StatefulComponent {
+        c := &StatefulComponent{
+        c.State.toggle = parentToggle
+        return c
+}

type MyComponent struct {
        vecty.Core
        ParentProp bool
}

func (c *MyComponent) Render() *vecty.HTML {
        return elem.Div(
-                &StatefulComponent{ParentToggle: c.ParentProp},
+                NewStatefulComponent(c.ParentProp),
        )
}
```

That is to say that the constructor would be responsible for props -> state propagation; which I think is also how this would be done in React (?).

With the above code, `MyComponent.Render` is effectively setting the toggle state of `StatefulComponent` initially, and then it's being fully managed by the component itself from that point onward (i.e. in all future renders).

If I look at the second code snippet for the problem you posted, however:

```Go
type StatefulComponent struct {
        vecty.Core
        ParentToggle bool
        State         struct {
                toggle bool
                parentToggle bool
        } `vecty:"state"`
}

func (c *StatefulComponent) Render() *vecty.HTML {
        if c.State.parentToggle != c.ParentToggle {
                c.State.toggle = c.ParentToggle
                c.State.parentToggle = c.ParentToggle
        }

        return elem.Button(
                vecty.If(!c.State.toggle, vecty.Text("Inactive")),
                vecty.If(c.State.toggle, vecty.Text("Active")),
                event.Click(c.toggle),
        )
}
```

I see that this would update `c.State.toggle` in the event that `c.ParentToggle` ever changes. This would mean that the actual problem this code tries to solve is:

> A parent component want's to specify the default toggle state for a toggle button component, which then of course changes it's own toggle state based on the user clicking the button. **+If the toggle state specified by the parent component changes, however, then the toggle state of the button component is overridden.**

If that is the desired behavior, however, then I can see why my suggestion of using a constructor would not work.

1. Which problem statement above is trying to be solved by your example code?
2. If trying to solve the second problem statement (parent always overrides child on value change), do you have a use case in mind where this would be used in the real world? I struggle to think of one right now (but I can imagine there may be one).
3. If trying to solve the second problem statement, I also wonder what React code would look like that attempts to solve this. Given React keeps a singular instance of the component around, how would it account for the prop toggle value provided by the parent changing after initial render?

---

> 2. Differences in behaviour between persistent component references and instantiating each render pass.
> ...
> I'm a little concerned that this difference in behaviour may be difficult to explain, and may be a source of confusion.

I do _really_ see your point there. This example by far casts the most doubt in my mind on the struct tag implementation I've suggested here.

For solving this issue, I can imagine two separate approaches:

1. (bad for various reasons) -> Try to find a way to ensure that persistent component references are not truly persistent but rather copied, and as such forcing that example to not work unless state fields were present. One example might be that instead of passing around component references, we could pass around anonymous functions / closures that render a component. I'm not exactly sure what this would look like right now, though, there may be obscure issues here or it may be non-obvious to users.
2. (best option, but hard to do) -> Ditch the struct tag idea, and try to come up with a way to make component references always persistent in a similar way to React.

Both of these options probably warrant a bit of investigation.

**Comment by slimsag** [comment]
(As someone who doesn't use React regularly, https://facebook.github.io/react/blog/2015/12/18/react-components-elements-and-instances.html has given me some good insight into what option #2 looks like in the React implementation)

**Comment by pdf** [comment]
Apologies if the example was a little contrived - I was trying to cover all the affected behaviours.

1. Your second problem statement describes what the 'correct' code implements
3. In React, you can do the initial props->state propagation in the constructor, however the lifecycle callback `componentWillReceiveProps` is triggered whenever a mounted component's props are updated from the parent. This allows modifying state on the back of a parent prop change.

---

Option 2 was indeed my first instinct, and I think we can probably do it, however that somewhat takes us back to https://github.com/gopherjs/vecty/issues/115#issuecomment-313816510 for trying to work out how to handle props set from the parent.  Part of the difficulty being that thanks to Go's zero values, it's not possible to tell whether a struct field has been explicitly set.

**Comment by slimsag** [comment]
I've been playing with an alternative idea I've had over the past ~5 hours or so; will update here soon.

**Comment by slimsag** [comment]
Ok, on second thought it will take a bit more work to actually get this working properly. There are a lot of edge cases to handle once I tried to actually make component instances persistent, so I didn't manage to get a working implementation in time. For now I'll have to settle with just outlining the approach here in text.

The idea is basically option 2, your first instinct. I think this could be a a really good approach. 

As you said, we must find a solution to how to handle props set from the parent / how to deal with Go zero values. My idea is basically that:

1. For the case of props->state propagation, we would use constructors. Of course, this isn't a strict requirement of this option. A component could just as easily do the more convoluted approach of keeping a second state value around as you showed in the second code snippet of https://github.com/gopherjs/vecty/issues/115#issuecomment-318805414
2. For the case of something like `componentWillReceiveProps`, we won't have something like that _right now_, but we can in the future consider adding something like this separately (and with this approach, it should be straightforward).
3. To solve the issue of Go zero values, we basically use the approach you described with point 3 _"Establish a convention that all public fields are always overwritten during render, and that internal state must use private fields."_, except with one additional requirement: that these fields have `vecty:"prop"` tags, since that appears less magical.

In the event that a user doesn't specify `vecty:"prop"` on a field that the parent component specifies, then they will notice that the value never changes even though the parent has changed the value it provides (this would happen because it is considered state unless tagged as a prop). I think in most cases this would be obvious enough behavior / something that could be addressed easily by a FAQ ("why doesn't my component see the value its parent component provides?").

What do you think?

**Comment by pdf** [comment]
Yeah, 3 is what I was getting at in https://github.com/gopherjs/vecty/issues/115#issuecomment-313918345 RE reversing the tag notation, I suspect you understand why I was thinking about that option now.

The implementation will not exactly be straight-forward, as you've discovered, but I do have some notions on how to get there.  Do you want me to leave this with you for now, since you've already started?

**Comment by slimsag** [comment]
I've sent https://github.com/gopherjs/vecty/pull/130 just now

> Yeah, 3 is what I was getting at in #115 (comment) RE reversing the tag notation, I suspect you understand why I was thinking about that option now.

Yes, sorry, it sounds like I misunderstood your initial idea. :/ Or I've forgotten about it and came to the same conclusion. Either way -- I think it's a good choice now :)
