### ISSUE TITLE
Is removing strconv feasible?

### ISSUE THREAD

**Issue by pdf** [gopherjs/vecty#144]
Per https://github.com/gopherjs/gopherjs/wiki/JavaScript-Tips-and-Gotchas the `fmt` package adds significant size to the transpiled code.  Current uses in Vecty appear pretty trivial, and can likely be replaced by https://github.com/cathalgarvey/fmtless or possibly alternative calls and string concat.

**Comment by slimsag** [comment]
Yeah, this is a good idea. May also be worth investigating removing our other two stdlib dependencies:

- `strconv` https://github.com/gopherjs/vecty/blob/master/style/style.go#L4
- `strings` https://github.com/gopherjs/vecty/blob/master/markup.go#L5

To start with I'd say keep it simple / don't pull in a dependency like fmtless

**Comment by pdf** [comment]
I'm pretty sure `strconv` is fine, would need to check `strings` in case it pulls in `fmt`.  The wiki notes that `fmt` increases output size by ~500KB... that's a _lot_.

**Comment by slimsag** [comment]
I did a quick check, one with an empty Go file just calling `println`, and three others just importing on package and calling a basic func in it.

```
$ du -sh ./*.js
 68K	./empty.js
780K	./fmt.js
108K	./strconv.js
100K	./strings.js
```

Almost certainly we can copy the relevant func that we actually use (or just use `js` package / browser API) to replace most of those easily. Our usages of them are pretty basic.

And a file importing all three:

```
792K	./fmtandstrconvandstrings.js
```

So we should be able to shave off ~700K by getting rid of those three.

Notably, those are not minified file sizes, but amount of code that must be parsed by browser is also important.

**Comment by pdf** [comment]
Ack, thanks for the tests, makes things pretty clear.  I actually ended up with 939K for `fmt` on Go1.9 :cry:

**Comment by slimsag** [comment]
I just retried with latest GopherJS binary & same Go version (go 1.9 darwin/amd64).

Without minification
```
$ du -sh ./*.js
 68K	./empty.js
924K	./fmt.js
936K	./fmtandstrconvandstrings.js
108K	./strconv.js
100K	./strings.js
```

With minification
```
$ du -sh ./*.js
 52K	./empty.js
624K	./fmt.js
632K	./fmtandstrconvandstrings.js
 80K	./strconv.js
 72K	./strings.js
```

**Comment by slimsag** [comment]
So that's ~868K we can save without minification, and ~580K with just by ditching those dependencies.

**Comment by shurcooL** [comment]
> Notably, those are not minified file sizes, but amount of code that must be parsed by browser is also important.

Did you mean not gzipped? Minifying reduces both the file size to transfer, and the size that must be parsed by browser. Gzipping only reduces file size to transfer but not what gets parsed in the end.

**Comment by shurcooL** [comment]
As far as I know, the absolutely only reason not to use minification is if you're debugging and want to look at GopherJS output. Compared to having minification on, having it off means inserting insignificant whitespace and making variable names longer (and more readable).

**Comment by shurcooL** [comment]
Also, that doing this will only help if the user of vecty _also_ doesn't import `fmt`, etc. Otherwise, it does not help.

**Comment by slimsag** [comment]
@shurcooL 

> > Notably, those are not minified file sizes, but amount of code that must be parsed by browser is also important.
>
> Did you mean not gzipped? Minifying reduces both the file size to transfer, and the size that must be parsed by browser. Gzipping only reduces file size to transfer but not what gets parsed in the end.

You're right that gzipping _also_ plays a role. But the size (in bytes) of code is not the only thing that affects browser parse time. For example, a browser could probably parse a javascript file with one string literal that is 1 MB pretty quickly, in contrast a 1 MB JS file of independent shorter string variables like `var one = "abc"`, `var two = "abc"`, repeated over and over again would probably be more costly to parse because it is producing more AST / being handled individually rather than just copied right into memory for example.

> As far as I know, the absolutely only reason not to use minification is if you're debugging and want to look at GopherJS output. Compared to having minification on, having it off means inserting insignificant whitespace and making variable names longer (and more readable).

Yep, I agree 100%. In fact, I would argue `gopherjs build` should produce minified output by default  instead of requiring `-m` or `--minify` flag to be present... after all, sourcemaps are better for debugging purposes generally speaking since it shows you Go code not JS code.

> Also, that doing this will only help if the user of vecty also doesn't import fmt, etc. Otherwise, it does not help.

Agreed. In general, I expect most users will probably end up with these dependencies, but this issue is about letting users who care use Vecty while not inherently having it pull in some large dependencies :)

**Comment by shurcooL** [comment]
I agree with the above.

However, I have concerns about this general direction and want to point them out. It's not that I think this shouldn't be done. I just want to explain why I don't think it's great.

Overall, I think doing this (removing `fmt` in vecty) is good in short term, but bad in long term.

First, you said:

> this issue is about letting users who care use Vecty while not inherently having it pull in some large dependencies

Are these users who use vecty and don't use `fmt` theoretical, or are you actually aware of projects that do this? Do you have statistics on how many people/projects do it?

I think it'd be very helpful if this issue is accompanied with some evidence for why this change should be done. It currently talks about hypothetical savings on projects that use/don't use `fmt`, which helps, but isn't the complete picture. If you know that 0 projects import vecty and don't import `fmt`, that paints a different picture compared to 20% or projects not importing `fmt`.

The most important disadvantage of this change, to me, is that it's against the spirit of Go. In normal Go, using fmt is normal and acceptable, and generally perceived that almost every Go package in the world will use it. So going out of the way to remove usages of it from a library is counter-productive. Vecty's description says:

> Vecty is a React-like library for GopherJS so that you can do frontend development in Go instead of writing JavaScript/HTML/CSS.

> Write everything in Go -- not JS/HTML/CSS!

Now imagine some Go user uses it and decides to contribute. Instead of seeing that Vecty is written in Go, they realize it's written in Go but has some unusual constraints. "Should I use "fmt" here, or is it deemed too expensive?"

Developing Vecty in the future becomes harder because it's going to be easy to accidentally introduce a "disallowed" standard library dependency. You could try to catch that with code review, or by adding automated tooling.

Anyway, I don't want to go over all the reasons why contributing to Vecty would become harder after this is implemented, that's already been discussed before in https://github.com/golang/go/issues/15583.

Finally, without knowing which users of vecty benefit from this removal of `fmt`, it's going to be hard to know when this decision should be revisited. Suppose all those 30% of projects that don't import `fmt` start to import it in 6 months from now. If you don't know those projects today, you won't know when that happens.

So, this is a -1 from me for the reasons stated above. However, it's not -2, and I think you should feel free to experiment with this change, I just want you to consider the downsides and be ready to re-evaluate whether this decision is a net positive or net negative to Vecty in the near future.

**Comment by shurcooL** [comment]
Also, to provide some data on Vecty users, I currently use it in 1 project, and that project most certainly imports `fmt`. It would not benefit from Vecty removing `fmt`:

- https://github.com/shurcooL/Go-Package-Store

**Comment by shurcooL** [comment]
Actually, I'll go further. I've looked at https://godoc.org/github.com/gopherjs/vecty?importers to find publicly known importers of vecty and checked which ones also import `fmt`:

-	[`github.com/iafan/goplayspace/client`](https://godoc.org/github.com/iafan/goplayspace/client?import-graph) - command, imports `fmt` ✅
-	[`github.com/iocat/youtube/example`](https://godoc.org/github.com/iocat/youtube/example?import-graph) - command, doesn't import `fmt` ❌
-	[`github.com/iocat/youtube/test`](https://godoc.org/github.com/iocat/youtube/test?import-graph) - command, doesn't import `fmt` ❌
-	[`github.com/shurcooL/Go-Package-Store/frontend`](https://godoc.org/github.com/shurcooL/Go-Package-Store/frontend?import-graph) - command, imports `fmt` ✅

I've only included commands, because it only matters whether the final command imports `fmt` or not, intermediate libraries don't matter.

So, as things currently stand, resolving this issue would benefit those 2 packages that also don't import `fmt` at this time (well, they do, but only through `vecty`).

**Comment by pdf** [comment]
@shurcooL wrote:
> The benefits of removing it are that commands that use vecty but not import fmt at all otherwise would have large savings of generated file size. It feels cool to save 500+ KB of output just by not importing fmt, I don't disagree there.

I think it's less that it feels _cool_ to enable a space saving, but that it feels _bad_ to be the cause of a space increase, particularly because the only uses of `fmt` in the Vecty code are for printing panics, that can be easily be replaced with string concat, and imports we need for core functionality.

> Now imagine some Go user uses it and decides to contribute. Instead of seeing that Vecty is written in Go, they realize it's written in Go but has some unusual constraints. "Should I use "fmt" here, or is it deemed too expensive?"
> 
> Developing Vecty in the future becomes harder because it's going to be easy to accidentally introduce a "disallowed" standard library dependency. You could try to catch that with code review, or by adding automated tooling.

This is certainly something to consider, it's why I haven't been overly enthusiastic with trying to remove _all_ stdlib imports.  The curly bit is that Go binary size is rarely a concern for most deployment scenarios, but for the web this is not the case.

Adding a test to CI would be a good idea if we do go ahead though.

> Finally, without knowing which users of vecty benefit from this removal of fmt, it's going to be hard to know when this decision should be revisited. Suppose all those 30% of projects that don't import fmt start to import it in 6 months from now. If you don't know those projects today, you won't know when that happens.

I think it's hard to try to use these metrics in isolation, since there are other factors to consider - are authors of these projects aware of the size impacts of importing `fmt` (I only stumbled upon the GopherJS wiki page the other day by accident)?  Have they determined that for their use-case, wire size doesn't matter?  Suppose that 6 months from now, all those projects have removed `fmt`, but Vecty remains a blocker to their size reduction?

As a library that aims to be a core component for web projects, I think Vecty has some obligation to try to be efficient (though not to a fault).  In the case of removing `fmt`, I think this is okay, unless/until there is some compelling use-case to pull it in.

**Comment by slimsag** [comment]
I've just merged https://github.com/gopherjs/vecty/pull/146 which does remove `fmt` and `strings` package dependencies.

@shurcooL I think you've raised some good points above, but from my perspective you see Vecty's stance here removing the fmt dependency as setting a precedent that users of Vecty should not use `fmt`. In contrast, I do not view this as such.

At a high level, I see this stance as setting a precedent that users of Vecty can choose if they do or do not use `fmt`, in just the same way that a user of `gopherjs` or the Go compiler isn't inherently tied to using a given set of dependencies (aside from the runtime).

Vecty itself doesn't really rely on `fmt` or other stdlib dependencies that much (and if it did, this change would likely not have gone through). Removing them doesn't really harm us. If not importing `fmt` leads to someone saying "well, I would contribute but I'm not sure how to workaround the disallowed fmt dependency.." then we can reevaluate or assist such a contributor directly.

I don't think every GopherJS package needs to outlaw `fmt`, but I also don't think Vecty should force `fmt` unless there is a good reason / strong usage of the package.

**Comment by pdf** [comment]
BTW, I checked the import graph, and `strconv` is required by `reflect`.

**Comment by slimsag** [comment]
@pdf Great! I think that concludes this issue then :)
