### ISSUE TITLE
Consider putting more emphasis on readable git history; use squash strategy when merging single-unit PRs.

### ISSUE THREAD

**Issue by shurcooL** [gopherjs/vecty#151]
This is simply a suggestion from a user and contributor to this (excellent) Go project about a way I think it can be made better.

I was recently updating to the latest version and looking over the history to see what changed. On `master` branch, I saw commit d593fc4cb952c55216fd0f9a28d195b34a5020cf, a revert commit, which did not describe the motivation for reverting a change (which is a bad practice, because it makes it really hard to understand why something was reverted for all other people). Upon further investigation, I saw that commit was actually a part of [PR #147](https://github.com/gopherjs/vecty/pull/147/commits), so nothing was actually reverted on `master`, it was just an internal detail of that PR.

In general, the git history of `master` branch has a low signal to noise ratio because of many commits with unhelpful subjects and commit message bodies. E.g.:

![untitled](https://user-images.githubusercontent.com/1924134/31062398-659b7894-a6f8-11e7-8f14-ebde1fcf2626.png)

It seems that most PRs here are made of commits that are just addressing internal PR feedback, rather than broken up into clean, logical and well documented separate commits to make the overall diff easier to understand. Yet they're merged via the "merge commit" strategy, which preserves individual PR commits with their original commit messages, resulting in the problem described above.

I suggest merging such PRs via the "squash merge" strategy, with a descriptive commit message that actually describes what changed on `master` and why. GitHub makes it easy ever since they've added this feature:

![image](https://user-images.githubusercontent.com/1924134/31062508-177eeab4-a6f9-11e7-8ddf-7268af0fc628.png)

![image](https://user-images.githubusercontent.com/1924134/31062559-73849c00-a6f9-11e7-8853-bfa7c9f52e4a.png)

For examples of what it can look like to have more readable git history, see:

- https://github.com/golang/go/commits/master
- https://github.com/golang/net/commits/master
- https://github.com/google/go-cmp/commits/master
- https://github.com/google/go-github/commits/master
- https://github.com/shurcooL/Go-Package-Store/commits/master

Thanks for consideration!

**Comment by shurcooL** [comment]
For reference, I was using GPS to see the updates, which exacerbates the situation. Compare:

![image](https://user-images.githubusercontent.com/1924134/31062666-5500c6cc-a6fa-11e7-9709-1229c6198287.png)

To something much more readable, like:

![image](https://user-images.githubusercontent.com/1924134/31062676-5f877b18-a6fa-11e7-8499-df21d964a7a4.png)

**Comment by slimsag** [comment]
Thanks for creating this @shurcooL -- I appreciate your attention to detail (especially since this more relates to how someone less involved in Vecty development might see / perceive Vecty).

Deciding the right strategy here is hard because sometimes changes / PRs do need to actually make two distinct changes from the perspective of the master branch. For example, if adding a new public function requires modifying an existing one. For these situations, what I will do from now on is write this detail into the squash merge commit message. I don't want to require contributors necessarily to create two distinct PRs in this case, since I wish to place more emphasis on code quality rather than git history.

But, to hopefully improve this issue as a whole, I've enabled GitHub's restrictions on merge/rebase commits, so that only squash merge is possible for me now:

![image](https://user-images.githubusercontent.com/3173176/31313803-e2fa171a-aba2-11e7-978e-d7cca31dce91.png)

We'll see if that helps improve our commit logicality overall. If it doesn't, we can try a different strategy :)

Closing for now.

**Comment by shurcooL** [comment]
Great, thanks a lot! I'm sure this will help significantly. Just make sure to review and edit the commit message title and body when merging PRs, so they contain only the information relevant to the final overall diff. You get a chance to easily modify them during the process of merging (this is one of the biggest benefits of this feature).

> Deciding the right strategy here is hard because sometimes changes / PRs do need to actually make two distinct changes from the perspective of the master branch.

In those cases, which as you mention are more rare, you could use rebase merge strategy, but it requires each commit to have a clean commit message. It won't give you a chance to edit them when merging.

**Comment by slimsag** [comment]
Will do! Good points all around :)
