### ISSUE TITLE
browser DOM refs

### ISSUE THREAD

**Issue by slimsag** [gopherjs/vecty#21]
The TodoMVC example currently does not select the text input when double clicking on an item. This is because we don't have any way to call `theInputElement.focus()` which in React would look something like:

```
ReactDOM.findDOMNode(this.refs.theInputElement).focus(); 
```

Need to figure out the right design for this.

**Comment by influx6** [comment]
Do we know of any form of event fired when a text input is selected by a input device, if we can attach to that and if that event is cross-browser then we can force an artificial focus onto any input element.

**Comment by shurcooL** [comment]
Maybe it's a "focus" event?

I've been in a situation where I was creating an "input" custom event on purpose, to trigger event listeners. See https://gotools.org/src.sourcegraph.com/apps/tracker/assets/script#main-go-L245.

Perhaps it can be something similar.

However, I think in this case, the problem is not the events that JS event listeners see, but having the browser actually give focus to the element so that typing letters on the keyboard results in text being entered in the input element. I haven't tested it, but I doubt this would work by creating a fake "focus" event.
