### ISSUE TITLE
Feature request: Basic DOM manipulation

### ISSUE THREAD

**Issue by AnikHasibul** [gopherjs/vecty#213]
In this interactive web era we must need to be interactive. xD
Vecty should add some jQuery equivalent `$("p").hide()` and `$("p").show()`.

I could do it with jQuery, but if there have something equivalent in vecty, I don't need to import a binding do use only two function!

WDYT?

**Comment by progrium** [comment]
I believe there are existing DOM implementations in Go that you can use to recreate jQuery-like functionality. Though it seems odd because you would approach doing that sort of thing very differently in this component paradigm. I'm not a maintainer but IMHO this seems out of scope for this project for several reasons.

**Comment by progrium** [comment]
I think the spirit of this post is about proper DOM bindings. There are only a couple of projects that attempts to provide coverage of the DOM in a native Go API, and many are not generating them. I'm keeping an eye out for this library and hope I don't have to write it, but after some work with Vecty I do think having DOM bindings would be nice.

**Comment by slimsag** [comment]
Vecty is strictly about _not_ applying arbitrary DOM operations yourself. As @progrium mentioned:

> In Vecty (or React or any component architecture), an element that you want to be able to hide, you'd keep it's visibility state in a component struct and then when you render you use that to decide if you render that element or not.

https://github.com/dominikh/go-js-dom is one such library that does implement DOM bindings, but I don't know the status of it at this time.

Since this issue seems to be mostly outside the scope of Vecty and it has been answered, I will close. Feel free to re-ask this on the GopherJS issue tracker or go-nuts mailing list instead.
