### ISSUE TITLE
Better list element reuse / "keys"

### ISSUE THREAD

**Issue by slimsag** [gopherjs/vecty#25]
See https://github.com/gopherjs/vecty/blob/master/dom.go#L114

**Comment by shurcooL** [comment]
@slimsag, you should post permalinks to lines in files. The `Y` shortcut is extremely helpful for making them. Using `master` branch means a line number is likely to point to something else after time passes and things shift around.

I went back to Feb 13th when the issue was created and found the commit you must've been referring to:

https://github.com/gopherjs/vecty/blob/8bd83c54933703ee2a802c6fcd39366b855a9e22/dom.go#L114

It pointed to a line containing `// TODO better list element reuse` comment. I can see that comment is still available in today's `master` some lines below:

https://github.com/gopherjs/vecty/blob/34ae77073fd923c6ab2f89c234a8ecf76f463cb0/dom.go#L159

(Feel free to edit your original issue and delete this comment to reduce noise, if you wish.)
