### ISSUE TITLE
Add TODOs Badge to README

### ISSUE THREAD

**Issue by patrickdevivo** [gopherjs/vecty#263]
Hi there! I wanted to propose adding the following badge to the README to indicate how many `TODO` comments are in this codebase:

[![TODOs](https://badgen.net/https/api.tickgit.com/badgen/github.com/gopherjs/vecty)](https://www.tickgit.com/browse?repo=github.com/gopherjs/vecty)

The badge links to `tickgit.com` which is a free service that indexes and displays TODO comments in public github repos. It can help surface latent work and be a way for contributors to find areas of code to improve, that might not be otherwise documented.

The markdown is:

```
[![TODOs](https://badgen.net/https/api.tickgit.com/badgen/github.com/gopherjs/vecty)](https://www.tickgit.com/browse?repo=github.com/gopherjs/vecty)
```

Thanks for considering, feel free to close this issue if it's not appropriate or you prefer not to!

(full disclosure, I am the creator/maintainer of `tickgit`)

**Comment by slimsag** [comment]
Hello, I do not believe that tracking TODOs in a README badge is a good idea:

1. What kind of signal does this send to repository consumers? "it has a lot of TODOs that the maintainers don't care about"
2. What is the goal? To reduce TODOs to zero?

I believe that people are increasingly and incorrectly viewing TODOs as _issues_ rather than _potential improvements_. I have personally seen this lead to a culture of "do not ever write TODOs because we should never write code that is imperfect" at various companies - which in reality just means people _do not communicate potential future improvements at all_ - or file GitHub issues that reference code that is then changed and moved around making the issue moot in the future.

I appreciate the suggestion and hope you take my feedback above in good faith - I will close this issue for now.
