### ISSUE TITLE
run TodoMVC tests

### ISSUE THREAD

**Issue by slimsag** [gopherjs/vecty#28]

**Comment by slimsag** [comment]
I haven't seen any good info yet on how TodoMVC handles testing; and think we should probably opt for just proper testing of Vecty instead of todomvc-specific testing. Please create a new issue if you think otherwise. :)

**Comment by chullino** [comment]
Bump! Is there any proper testing of Vecty based application? 

Currently, I'm working on creating test code for Vecty-based web app. 

I'm assured that I can create react-like code using Vecty, and I'm assured that I can test HTML GET API is working well, but **I'm not sure if I can test rendered HTML to validate my vecty-generated HTML.**

To speak with (bloated :<) example, I can create react-like code using Vecty like below. When this code is transpiled to JS and executed on the browser, **it will create left-floated red box written "Hello Vecty!"**.
```
// Render &PageView{} into div element with id `vecty-content`
func main() {
	vecty.SetTitle("Hello Vecty!")
	err := vecty.RenderInto("#vecty-content", &PageView{})
	if err!= nil{
		panic(err)
	}
}

// PageView is our main page component.
type PageView struct {
	vecty.Core
}

// Render implements the vecty.Component interface.
func (p *PageView) Render() vecty.ComponentOrHTML {
	return elem.Div(
		vecty.Markup(
			vecty.Style("float", "left"),
			vecty.Style("background-color", "red"),
		),
		vecty.Text("Hello Vecty!"),
	)
}
```

Also, I can test HTML GET API is working well using httptest. `performRequest` function is used for http test.

```
func Test_All_Routes_Status_200(t *testing.T) {
        // Setup router
	router := setUp()
	
	// data for test
	tests := []string {
		"/vecty",
	}
	
	for _, test := range tests {
		t.Run(test, func(t *testing.T) {
			// Perform a GET request with that handler.
			res := performRequest(router, "GET", test)
			// Assert we encoded correctly, the request gives a 200
			assert.Equal(t, http.StatusOK, res.Code)
		})
	}
}

func performRequest(r http.Handler, method, path string) *httptest.ResponseRecorder {
    req, _ := http.NewRequest(method, path, nil)
	res := httptest.NewRecorder()
	r.ServeHTTP(res, req)
	return res
}
```

But the problem is that I have no idea on how to test rendered HTML. For example, I have HTML like this.
```
{{define "vecty.html"}}
    <html>
		<body>
			{{template "header.tmpl" .}}
			{{template "navBar.tmpl"}}
			{{template "contents.tmpl" .}}
			<div id="vecty-content"></div>
  			<script src="/static/templates/vecty/scripts/scripts.js"></script>
		</body>
    </html>
{{end}}
```

Currently I'm beating my head against wall to render left-floated box written "Hello Vecty!" into div element whose id is vecty-content, but ended with no results.

**Comment by nathanhack** [comment]
@chullino I'm not an authority on Vecty nor a web guru but given your question I think of two things you could test.

1) in a test, setup your component and compare the render output to what you expect.  
2) in a test, setup your server and request the page then compare to something expected.

The first one is a unit test and the second one is more of a integration test. 

There is talk of adding server side rendering https://github.com/gopherjs/vecty/issues/23 to Vecty.  I think once that was completed then doing what your asking for will be easy.
