### ISSUE TITLE
debugging

### ISSUE THREAD

**Issue by joeblew99** [gopherjs/vecty#44]
I am curious about debugging the example.
I am using Delve.

example.go is the main starting point.
````
func main() {
	attachLocalStorage()
````

but it immediately jumps to runtime.go, line 506
````
//go:nosplit
func startpanic() {
	systemstack(startpanic_m)
}
```
Because this is dependent on the DOM for rendering, does it mean its basically not possible to debug it as golang ?

The reason i am doing this is to see basically see how easy it is to debug and test golang code that is destined to be compiled to JS, before its JS

**Comment by joeblew99** [comment]
Its seems its just not possible ?
https://github.com/gopherjs/gopherjs/blob/master/doc/packages.md

**Comment by bep** [comment]
I'm confused as to what you expect? The runtime is JavaScript -- so you would need a JavaScript debugger, not a Go debugger.

**Comment by joeblew99** [comment]
thats not really helpful to me.
Its stil golang code, but i am not sure if its dependencies at runtime means its not going to really be able to run as golang code. Hence, why i asked if the DOm dependency blows it up.

The intent is to see how much code can be shared client server. Where is the boundary, and what can be tested as pure golang code. This is important to me for larger projects where code is shared.

Hope that helps illustrate why i am asking ? Would be good to know what you feel is pertinent to my endeavour

**Comment by shurcooL** [comment]
If you look at how Delve was developed, it makes heavy use of the operating system signals and other low level things. Adding support for OS X was a major mount of work, and relied heavily on specifics of OS X.

Unless Delve happened to also do the work to support debugging JavaScript applications, it will not be able to debug Go programs cross-compiled with `js` architecture. I don't know if @derekparker is even familiar with the GopherJS compiler. But in any case, I'm quite sure debugging JavaScript was out of its scope. To my (limited) knowledge, it does not do that.

You'd probably get a more direct answer to your question if you asked it on Delve forums.

**Comment by joeblew99** [comment]
hey @shurcooL 

i know what your mean. 

my intent is really to try to understand the isolation aspects. What i mean by this is what golang code can be run (and my its nature debugged) NOT as javascript.
For example, i am playing around with different ways of developing apps (desktop, mobile and web9 with gopherjs. I just started on gopherjs, and so my knowledge is limited on its architectural aspects.
Now, the architectural opportunity is reuse and DRY principles, which i feel is worth allot.

SO, the questions is to do with what code can be expected to be reused across the client and server ?
And its not just about code reuse, Its about testability of that code. For example, code (like vecty), because its simulating react, and hence relies on the DOM being there, has very little chance that it can be run on the server, and so then tested with either a test harness or unit testing. Is my assumption correct here ?

Hope you can see what i am getting at here .

**Comment by shurcooL** [comment]
> Now, the architectural opportunity is reuse and DRY principles, which i feel is worth allot.
>
> SO, the questions is to do with what code can be expected to be reused across the client and server ?
And its not just about code reuse, Its about testability of that code.

I can tell you everything I know about testing frontend stuff with GopherJS. It's not a lot. I think it's a hard problem. It's also important. But I have to do many other things before I can focus my attention on this, that's why I haven't gotten to it yet.

For now, all my GopherJS/frontend tests are simply unit tests for things that don't depend on the DOM. For example, see [`date_test.go`](https://github.com/shurcooL/resume/blob/c1ce59ab30809e8908ad6b1be7724f309356344d/date_test.go). With those kind of tests, I can just run them with `go test` fine. Or `gopherjs test`, it makes no difference. Aside from that, the most frontend-y tests I'm familiar with are the JUnit one like in https://github.com/gopherjs/websocket/tree/master/test. But because they're so hard to run and automate, I rarely actually run them.

> For example, code (like vecty), because its simulating react, and hence relies on the DOM being there, has very little chance that it can be run on the server, and so then tested with either a test harness or unit testing. Is my assumption correct here ?

That sounds accurate to me. To test something that uses DOM, you need something that provides a DOM. Either the browser, or another implementation. Obviously, implementing all of DOM yourself reliably and fully is non-trivial.

**Comment by joeblew99** [comment]
super useful, and makes sense. i just needed a sanity check. thanks.

i was looking for gopherjs test examples. all i found were issues open around it.

related to this all is the work your doing on getting gopherjs to match or use the standard go build idioms. i saw a bunch of issues tagged with things that would be way easier if gopherjs used the standard go build infrastructure. i would very much like to get more insight on this.
if you have urls could you throw some here ? i might be able to help, since gopherjs and gomobile are used at work

**Comment by slimsag** [comment]
I've only skimmed this thread because it is so lengthy, so if i miss something forgive me.

1. Have you checked out godebug which works well with gopherjs so I am told? http://blog.mailgun.com/introducing-a-new-cross-platform-debugger-for-go/
2. Whether or not Vecty can be run entirely in a gc-toolchain environment (without a real browser) is an interesting prospect, but the devil is in the details. I haven't played around in this area enough to say for certain which way the tree will fall.

**Comment by gedw99** [comment]
Thanks for the responses.

@slimsag i will look into that option. Its a good idea that i tried a while ago. I will keep playing around and try to make progress.

@shurcooL I am playing around with takin the approach of building gopherJS apps that have a distinct architecture to make things workable. It might not be everyones cup of tea, but its simple.
**Proxy Server code.** 
This is golang code that is "transpiled" to the communications, Structs, Structs Validation done. This code in in the "shared" folder / namespace, so its clear that its "deployed" on both the client and server. I am stil in 2 minds about about the best RPC style; GRPC, some custom code gen, or hand writing the code in golang before transpiling. The Fetch API is attractive but that rules out RPC. The JSONRPC over web sockets looks good (JSONRPC is transort agnostic, and so gives me options also).
GRPC is nice, but as far as i can see it will not support Web browsers ( no frame headers).

 **DOM Code.**
This is golang code that is DOM dependent. It goes in the "client" folder / namespace. Its dependent on browser based unit testing tools. It might use some bindings to react or other DOM related things.

In the end this gets me a clear demarcation of a number fo architectural aspects, including the original topic of Debugging. 

I will try to get some stuff up on github and the web, and welcome everyones thoughts.

**Comment by slimsag** [comment]
Could we hone this issue into some concrete actions or problems? I'd be glad to help out find the best way forward here.. but it's not entirely clear to me what this issue is about (it seems to be mixed discussion of debugging techniques in addition to how to lay out code compiled by GopherJS and Go).

If this isn't an issue but rather general discussion, maybe it would be better done in the [Slack channel](https://github.com/gopherjs/vecty#community) or if that's not suitable maybe this issue should be about having a mailing list?

**Comment by joeblew99** [comment]
i started it, and it was more of a general discussion.

So i am happy to close it. It should not be here.
