### ISSUE TITLE
Error when view TagName changes

### ISSUE THREAD

**Issue by davelondon** [gopherjs/vecty#60]
Consider the modified todomvc example in the `replacechild` branch of `github.com/davelondon/vecty`.

```
go get -u github.com/davelondon/vecty
cd $GOPATH/src/github.com/davelondon/vecty
git checkout replacechild
gopherjs serve
open http://localhost:8080/github.com/davelondon/vecty/examples/todomvc/
```

The example is a simple `TestView` that returns an `elem.Div` or `elem.Paragraph`. Buttons control the tag that is emitted and a counter. Changing the tag causes a Javascript error:

```
Uncaught TypeError: Cannot read property 'replaceChild' of null
```

This can be fixed by [this commit](https://github.com/davelondon/vecty/commit/df4daee7023bc4a66a230d6255b7026521509786) in the `replacechild-fixed` branch. However I think there may be a better way. By the time [this reconcile](https://github.com/davelondon/vecty/blob/master/dom.go#L151) has finished, `newChild` has already replaced `oldChild` in the parent element, so `oldNode.Get("parentNode")` is `null`. I'm not entirely sure why this is, but stopping this may be better than preventing the `replaceChild` operation?

**Comment by slimsag** [comment]
Hey Dave,

The first thing I noticed was that your branch was quite out of date (20 commits behind, from before we did the major architecture change). Nonetheless, I went ahead and reapplied your work on the latest `master` as of today (see my `issue60` branch at https://github.com/slimsag/vecty).

As far as I can tell, it works exactly as expected on the new architecture / doesn't have the issue you are describing. Here's a gif of me clicking the various buttons and it changing from div <-> p (there also aren't any console errors, either)

![gif](http://g.recordit.co/jt9yPID4rk.gif)

I think this was just a bug in the old codebase -- but not in the new one. If you think otherwise please let me know, I'm glad to look into this further :)

P.S. apologies for the delay on this! Cheers!
