### ISSUE TITLE
"Getting started" does not exist (TodoMVC example panics when not running with GopherJS..)

### ISSUE THREAD

**Issue by campoy** [gopherjs/vecty#61]
Hi there,

I'm considering using gopherJS and vecty for a small webpage I need to write, my first experience was pretty disappointing:

``` bash
$ go get github.com/gopherjs/vecty/examples/todomvc
$ todomvc
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x71242]

goroutine 1 [running]:
panic(0xc55e0, 0x15a030)
    /Users/campoy/src/golang.org/x/go/src/runtime/panic.go:496 +0x1a0
github.com/gopherjs/gopherjs/js.(*Object).Get(0x0, 0xe172c, 0xc, 0xe7b40)
    /Users/campoy/src/github.com/gopherjs/gopherjs/js/js.go:32 +0x22
main.attachLocalStorage()
    /Users/campoy/src/github.com/gopherjs/vecty/examples/todomvc/example.go:39 +0x74
main.main()
    /Users/campoy/src/github.com/gopherjs/vecty/examples/todomvc/example.go:17 +0x26
```

I have really not much of an idea of how to make it work, maybe some instructions on a `README.md` in the todomvc directory might help?

Francesc

**Comment by shurcooL** [comment]
Documentation can certainly be improved, given this project might be seen by people who are not yet familiar with using Go in the browser and GopherJS.

That said, it seems to be you're trying to execute the `github.com/gopherjs/vecty/examples/todomvc` Go package on the backend, but the package is meant to run inside the browser. It panics because the DOM isn't available.

You should compile the package to target the browser using gopherjs:

```bash
# Download the package and its dependencies.
GOARCH=js go get -u -d github.com/gopherjs/vecty/examples/todomvc

# Build using GopherJS compiler.
gopherjs build github.com/gopherjs/vecty/examples/todomvc
```

That'll produce the output named `todomvc.js` in your current directory. Running that inside the browser should work without panicking.

**Comment by davelondon** [comment]
Or of course even easier for testing you can just run `gopherjs serve` and open http://localhost:8080/github.com/gopherjs/vecty/examples/todomvc/ in your browser. That will compile todomvc to js and serve it in an empty page.

**Comment by slimsag** [comment]
- @campoy sorry to hear you had a bad first experience. If the comments here didn't clear up the issue, please let me know (you need to run it with GopherJS, not the standard Go compiler).
- As for getting started docs, let's fold that into issue #31 
- Improved errors is being discussed in gopherjs/gopherjs#542 which looks quite nice.
- I may consider adding a special file to Vecty which panics on init for a more immediate fix. Will close this issue if I decide against it.
