### ISSUE TITLE
panic when DOM is not present

### ISSUE THREAD

**Issue by hemantasapkota** [gopherjs/vecty#74]
Hi, I wanted to do a quick preview for Vecty but seems like I can't get the markdown demo to run.

```
➜  markdown git:(master) ✗ gopherjs run markdown.go
gopherjs: Source maps disabled. Use Node.js 4.x with source-map-support module for nice stack traces.
/Users/hemantasapkota/go/src/vecty/examples/markdown/markdown.go.063081130:1475
        throw err;
        ^

TypeError: Cannot set property 'title' of undefined
    at Object.$packages.github.com/gopherjs/vecty.SetTitle (/Users/hemantasapkota/go/src/vecty/examples/markdown/markdown.go.063081130:18621:26)
    at $packages.main.main (/Users/hemantasapkota/go/src/vecty/examples/markdown/markdown.go.063081130:36062:9)
    at $packages.main.$init (/Users/hemantasapkota/go/src/vecty/examples/markdown/markdown.go.063081130:36127:9)
    at $goroutine (/Users/hemantasapkota/go/src/vecty/examples/markdown/markdown.go.063081130:1466:19)
    at $schedule (/Users/hemantasapkota/go/src/vecty/examples/markdown/markdown.go.063081130:1523:5)
    at $go (/Users/hemantasapkota/go/src/vecty/examples/markdown/markdown.go.063081130:1499:3)
    at Object.<anonymous> (/Users/hemantasapkota/go/src/vecty/examples/markdown/markdown.go.063081130:36138:1)
    at Object.<anonymous> (/Users/hemantasapkota/go/src/vecty/examples/markdown/markdown.go.063081130:36141:4)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:138:18)
    at node.js:974:3
➜
```

**Comment by slimsag** [comment]
Try `gopherjs serve` and then navigate to http://localhost:8080/github.com/gopherjs/vecty/examples/markdown/

Does that work? (I presume `gopherjs run` is like `go run` and hence doesn't do what you expect -- it runs only that one file without dependencies or something..)

**Comment by hemantasapkota** [comment]
Awesome. That worked. Thanks for speedy response.

**Comment by slimsag** [comment]
@hemantasapkota awesome :)

@shurcooL would you expect gopherjs to provide a better error message here? or no? I can file an issue if so

**Comment by shurcooL** [comment]
What would be a better error?

The error happens on this line:

```Go
js.Global.Get("document").Set("title", title)
```

node's global object doesn't have `document` and returns `undefined`. Setting `title` on `undefined` causes:

```
TypeError: Cannot set property 'title' of undefined
```

It looks like the problem here was a misunderstanding of environments where a Go program compiled to JavaScript can run. That Go package was meant to be run inside of a browser, not in the terminal via node. I usually document such packages to say that.

**Comment by slimsag** [comment]
Oh, wow, oops, sorry @shurcooL ! And thank you!

I tagged you but it seems I didn't fully understand the issue at hand. I had (very wrongly) thought that `gopherjs run markdown.go` somehow left out another Go file like when using `go run a.go` with `b.go` in the same directory -- and that GopherJS somehow tried to 'best-effort' run it (I was surprised it got past compilation). I see now it was purely due to the runtime `js` calls -- not due to missing Go code -- as you said.

I imagine to prevent users from running into this by accident I could add a panic if `js.Global.Get("document") == undefined`, similar to what I've done in https://github.com/gopherjs/vecty/blob/master/gopherjs_only.go -- that might be better than just documenting the package as such.

**Comment by anxiousmodernman** [comment]
This particular error occurred on `SetTitle`, but not everyone will call this function when they're getting started. They might jump straight to `RenderBody`, or the planned `RenderInto`, etc.

Package-level `init` is one place to do this, perhaps the only place. Alternatively, you might have some kind of new function, `vecty.BrowserInit`, but then everyone would need to call this.

FWIW, I might caution against adding environment checks like this in vecty. If you have a goal to be able to run _unit tests_ against vecty code in a non-browser environment, or do server side rendering, it may not be possible to do these kinds of environment checks in a way that works for every use case, existing or planned.

**Comment by slimsag** [comment]
We already do some environment checks such as https://github.com/gopherjs/vecty/blob/master/gopherjs_only.go so I don't think environment checks are bad. I've already proven they can work properly with unit tests, as well (haven't pushed this code yet, though). For sure, if/when we support server side rendering we'd have to relax the constraints.

I think this would be as simple as placing a check for `document == null` (psuedocode) inside `init`.
