### ISSUE TITLE
ClassMap appension

### ISSUE THREAD

**Issue by slimsag** [gopherjs/vecty#80]
See https://www.reddit.com/r/golang/comments/5qjxve/qlql_qlgopherjsvectyelectron_a_gui_for_ql_to/dczvrie/?st=iygkrkdy&sh=9aa5953a for details.

**Comment by gernest** [comment]
I think the behavior of `ClassMap` can stay unchanged. Instead we need to add Another separate function which will behave as appending to existing classes. something like `AddClass` this way users can pick whatever they see fits.

**Comment by pdf** [comment]
I've been experimenting a little with component libraries, and being able to append classes is really a necessity to enable that pattern.  I think I'd be fine with both class-related functions just appending by default.  Is there an obvious downside to that approach?

**Comment by slimsag** [comment]
@pdf coming back to this several months later, I forget what this issue was about and the chain of comments here is not that easy to decipher.

If I understand it correctly, the goal is to have some way for multiple classes to be applied to the same element when specified independently / not in one `ClassMap` or `prop.Class`, does that sound right to you? If so:

1. I do not think that `prop.Class` should be changed. It is just setting `className` and the user is responsible for using that however they choose. Most users, I expect, will not use this function unless they just need to set a few class names via a string literal.
2. I am OK with changing `ClassMap` to be appension by default, something like how `dataset` is handled https://github.com/gopherjs/vecty/blob/master/markup.go#L133-L140 sounds good to me.

> `ClassMap` would maybe be a little more complicated, since you may want override an enabled class.

Please elaborate on this, as I don't understand what you mean.

**Comment by pdf** [comment]
Basic premise sounds right.  Here's a quick-and-dirty example (slightly complex, but hopefully not _too_ difficult to follow) of where it gets problematic in a hypothetical component framework, where we want to compose classes:

```go
// Package component contains the framework-internal component
package component

type MyComponent struct {
  vecty.Component
  Markup []vecty.MarkupOrChild `vecty:"prop"`
}

func (c *MyComponent) Render() *vecty.HTML {
  return elem.Div(
    append([]vecty.MarkupOrChild{
      vecty.Markup(vecty.Class("mycomponent-class"),
    }, c.Markup...)...,
  )
}
```

```go
// Package public exposes the public API
package public

// ComponentFunc exposes a func that wraps the component, to provide an elem-like API
func ComponentFunc(markup ...vecty.MarkupOrChild) vecty.Component {
  return &component.MyComponent{Markup: markup}
}
```

```go
// Package usercode is the end-user's code
package usercode

type Body struct {
  vecty.Core
}

func (c *Body) Render() *vecty.HTML {
  return elem.Body(
    public.ComponentFunc(
      vecty.Markup(
        vecty.Class("custom-class"),
      ),
      vecty.Text("hello"),
    ),
  )
}
```

The `public` and `component` packages don't need to be separate, but I wanted to make clear what the `public` API might look like for this hypothetical framework.

I think the desired result here would be for `ComponentFunc` to end up rendering `MyComponent->div` with both `mycomponent-class` and `custom-class`.  Of course, it would be possible to write this using `ClassMap` only, in the case that `ClassMap` supports composition, but this still leaves things awkward for the end-user, since they break the framework's styles if they inadvertently use `Class` instead of `ClassMap`.

If `Class` stays as it is, I think it absolutely needs to be explicit in its documentation that it overrides all other class definitions and that its use is discouraged, though it would still be nice to have a shorthand for adding classes, perhaps `AddClass` as @gernest suggests, or perhaps `Class` changes behaviour, and there's a separate func for resetting/overwriting classes.

---

> Please elaborate on this, as I don't understand what you mean.

If `ClassMap` worked similar to `dataset`, that would solve the issue I was talking about - I just meant that you couldn't simply append the current `ClassMap` text result.

**Comment by slimsag** [comment]
Makes perfect sense. I appreciate the detailed write-up.

I didn't think about external users overwriting internal library classes with `prop.Class` before your comment here, I see the concern now and I agree that is a problem worth solving.

What I'd like for us to do here:

1. Make `ClassMap` work like `dataset`.
2. Remove `prop.Class` and add `vecty.Class` which does the same thing but with appension. Removing it from `prop` is important because it is no longer setting a property. We could leave it, but that would just lead to confusion, so I say let's remove it.

Maybe with `vecty.Class` (which would be implemented kind of like how https://godoc.org/github.com/gopherjs/vecty#Data is implemented), `ClassMap` could also be simplified in implementation, but I am not sure about this.

**Comment by pdf** [comment]
How would you feel about using [classList](https://caniuse.com/#feat=classlist)?  Support is pretty good everywhere GopherJS is supported, except for SVG/MathML quirks on IE11/Opera Mini.

It maps much better than dealing with `className`.

**Comment by slimsag** [comment]
Only had a few mins to look, but it seems like the ideal choice for fixing
this issue, yep. I think the IE 11 SVG/ML issue is not an issue.
