### ISSUE TITLE
"Uncaught TypeError: Cannot read property 'style' of null" panic when Restorer interface implemented.

### ISSUE THREAD

**Issue by shurcooL** [gopherjs/vecty#92]
I'm new to vecty, and I'm in the process of learning it and becoming more familiar with its features. I may be doing something illegal without realizing it, or this could be a bug in vecty implementation.

My implementation of `Restorer` looks like this:

```Go

type PresentationChanges struct {
	vecty.Core
	*model.RepoPresentation // Only uses Changes, and if len(Changes) == 0, then LocalRevision and RemoteRevision.
}

// Restore is called when the component should restore itself against a
// previous instance of a component. The previous component may be nil or
// of a different type than this Restorer itself, thus a type assertion
// should be used.
//
// If skip = true is returned, restoration of this component's body is
// skipped. That is, the component is not rerendered. If the component can
// prove when Restore is called that the HTML rendered by Component.Render
// would not change, true should be returned.
func (p *PresentationChanges) Restore(prev vecty.Component) (skip bool) {
	old, ok := prev.(*PresentationChanges)
	if !ok {
		return false
	}
	return old.RepoPresentation == p.RepoPresentation
}
```

The panic looks like this:

![image](https://cloud.githubusercontent.com/assets/1924134/23536723/e4914fd6-ff94-11e6-9e60-2a6f861cabaf.png)

It happens on this line:

```Go
style := h.Node.Get("style")
```

Inside `func (h *HTML) restoreHTML(prev *HTML)`, because `prev.Node` is `nil`, which gets assigned to `h.Node` on first line of `restoreHTML`.

### Reproduce

No smaller repro for now, but it should be very easy to repro with a large project. Here are the steps:

1. `go get -u -d github.com/shurcooL/Go-Package-Store/cmd/Go-Package-Store`.
2. `cd` into the repository and checkout latest version of `frontend-vecty-issue-92` branch.
3. Modify hardcoded path in line 19 of `./cmd/Go-Package-Store/updates.go` file to one that matches your local setup (sorry, it's a temporary development artifact).
4. `go build -tags=dev github.com/shurcooL/Go-Package-Store/cmd/Go-Package-Store`
5. Execute `Go-Package-Store` binary.
6. Open http://localhost:7043/updates in a browser.
7. You'll see [this](https://cloud.githubusercontent.com/assets/1924134/23536870/0a00ce62-ff96-11e6-89bd-7a9ad2ec62e9.png).
8. Click top-most "Update" button (not Update All).
9. You'll see [this](https://cloud.githubusercontent.com/assets/1924134/23536884/29da1db0-ff96-11e6-89f8-bd773c53f5fb.png).
10. Note that if you press the bottom-most "Update" button, no panic.

**Comment by slimsag** [comment]
Sorry that I still haven't had time to investigate this fully, I've been very swamped with other things in life. I still need to recreate a small test case for this before I can fix.

**Comment by pdf** [comment]
@shurcooL I don't believe Restorer is functional on Rerender for Components currently anyway - I've filed #106 for that.

**Comment by slimsag** [comment]
Just wanted to post an update here: I've reproduced the issue exactly as described against the latest `master` branch (i.e. #114 does _not_ fix this issue).

I've forked & updated the original branch to show the issue @ latest master, however: https://github.com/slimsag/Go-Package-Store/commits/frontend-vecty-issue-92

It should be noted, however, that `SkipRender` won't actually help your `PresentationChanges` component render faster when the user clicks your `Update` button. This is because, right now at least, the list of `PresentationChanges` is removing items from the top, and Vecty doesn't yet have a Key-based sorting thing implemented (as you saw in https://github.com/gopherjs/vecty/pull/107).

I plan to at a later date take a look at how G-P-S uses Vecty and ensure it's working optimally there :)

**Comment by slimsag** [comment]
@shurcooL I just tried this out again against the latest master, which has a lot of improvements from @pdf , and found that this issue seems to no longer occur. I think it was fixed by https://github.com/gopherjs/vecty/pull/122 and/or https://github.com/gopherjs/vecty/pull/124

Would you be willing to re-run the updated branch I created above (https://github.com/slimsag/Go-Package-Store/commits/frontend-vecty-issue-92) and confirm that it looks okay? I ask because I'm not 100% familiar with the G-P-S user interface as I haven't used it in a long while.

**Comment by shurcooL** [comment]
I can certainly try. How is your branch different from my branch with same name?

**Comment by slimsag** [comment]
> Edit: I think I see, you updated it to match latest API changes in vecty.

Correct

**Comment by shurcooL** [comment]
I've tried it out, I can confirm it no longer panics.

I think we can consider this issue resolved, so I'll close it now. Thank you @slimsag and @pdf!

When I revisit this code, if I run into anything else, I will report it.

**Comment by slimsag** [comment]
Thanks for confirming @shurcooL!
